version: "3"
services:

  pv_simulator:
    build: ./pv_simulator
    environment:
      WAIT_HOSTS: host.docker.internal:5672
    depends_on:
      - meter
      - rabbitmq

  meter:
    build: ./meter
    environment:
      WAIT_HOSTS: host.docker.internal:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - "rabbitmq_data:/data"

volumes:
  rabbitmq_data:
      driver: local


